package com.example.dotabuffapp;

enum ItemsPool {
    PhaseBoots,
    MagicWand,
    BlinkDagger,
    BlackKingBar,
    AghanimsScepter,
    PowerTreads,
    ArcaneBoots,
    WraithBand,
    TranquilBoots,
    NullTalisman,
    BootsOfTravel,
    AetherLens,
    HandOfMidas,
    Bracer,
    BladeMail,
    ForceStaff,
    EulsScepterOfDivinity,
    Maelstrom, //?
    Desolator,
    MonkeyKingBar,
    Mjollnir,
    ShadowBlade,
    MantaStyle,
    GlimmerCape,
    Radiance,
    PipeOfInsight,
    EchoSabre,
    DiffusalBlade,
    SoulRing,
    RodOfAtos,
    SpiritVessel,
    AssaultCuirass,
    SkullBasher, //?
    GhostScepter, //?
    HeartOfTarrasque,
    AbyssalBlade,
    GuardianGreaves,
    Daedalus,
    LinkensSphere,
    HurricanePike,
    Butterfly,
    ScytheOfVyse,
    Kaya,
    CrimsonGuard,
    BattleFury,
    DrumOfEndurance,
    VladmirsOffering,
    RingOfBasilius, //?
    SilverEdge,
    SolarCrest,
    SangeAndYasha,
    EyeOfSkadi,
    LotusOrb,
    VeilOfDiscord,
    MaskOfMadness,
    EtherealBlade,
    ShivasGuard,
    OrchidMalevolence,
    AeonDisk,
    Satanic,
    ArmletOfMordiggian,
    YashaAndKaya,
    Bloodthorn,
    OctarineCore,
    RefresherOrb,
    HeavensHalberd,
    Mekansm, //?
    Bloodstone,
    MoonShard,
    Dagon5,
    Nullifier,
    KayaAndSange,
    MeteorHammer,
    DivineRapier, //?
    HelmOfTheDominator,
    Necronomicon3,
    HolyLocket,
    Dagon, //?
    Dagon3, //?
    Dagon2, //?
    Dagon4, //?
    Necronomicon, //?
    Necronomicon2 //?
}