package com.example.dotabuffapp;

enum ItemsPool {
    MagicWand,
    PowerTreads,
    BlackKingBar,
    BlinkDagger,
    AghanimsScepter,
    PhaseBoots,
    TranquilBoots,
    ArcaneBoots,
    AetherLens,
    NullTalisman,
    BootsOfTravel,
    ForceStaff,
    WraithBand,
    SilverEdge,
    EulsScepterOfDivinity,
    Bracer,
    SoulRing,
    MantaStyle,
    Maelstrom, //?
    GlimmerCape,
    BladeMail,
    Desolator,
    EchoSabre,
    SkullBasher, //?
    EyeOfSkadi,
    Daedalus,
    MonkeyKingBar,
    GhostScepter, //?
    HandOfMidas,
    Satanic,
    DragonLance, //?
    SangeAndYasha,
    OrbOfCorrosion,
    AeonDisk,
    BattleFury,
    AbyssalBlade,
    ArmletOfMordiggian,
    ShadowBlade,
    OrchidMalevolence,
    HeartOfTarrasque,
    SpiritVessel,
    AssaultCuirass,
    HurricanePike,
    LinkensSphere,
    MaskOfMadness,
    Mjollnir,
    RodOfAtos,
    HeavensHalberd,
    DiffusalBlade,
    LotusOrb,
    OctarineCore,
    ScytheOfVyse,
    Butterfly,
    GuardianGreaves,
    PipeOfInsight,
    RefresherOrb,
    FalconBlade,
    ShivasGuard,
    EtherealBlade,
    KayaAndSange,
    Gleipnir,
    Kaya,
    Radiance,
    EternalShroud,
    Bloodthorn,
    WitchBlade,
    SolarCrest,
    Bloodstone,
    VeilOfDiscord,
    MeteorHammer,
    OverwhelmingBlink,
    CrimsonGuard,
    Mekansm, //?
    MoonShard,
    HolyLocket,
    SwiftBlink,
    ArcaneBlink,
    VladmirsOffering,
    Dagon5,
    BootsOfTravel2,
    YashaAndKaya,
    Nullifier,
    DivineRapier, //?
    MageSlayer,
    DrumOfEndurance,
    WindWaker,
    Dagon, //?
    HelmOfTheOverlord,
    HelmOfTheDominator
}